# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"7\n\x12PredictionResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x99\x01\n\x10InferenceService\x12\x41\n\x07Predict\x12\x17.inference.ImageRequest\x1a\x1d.inference.PredictionResponse\x12\x42\n\x0bHealthCheck\x12\x18.inference.HealthRequest\x1a\x19.inference.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=30
  _globals['_IMAGEREQUEST']._serialized_end=64
  _globals['_PREDICTIONRESPONSE']._serialized_start=66
  _globals['_PREDICTIONRESPONSE']._serialized_end=121
  _globals['_HEALTHREQUEST']._serialized_start=123
  _globals['_HEALTHREQUEST']._serialized_end=138
  _globals['_HEALTHRESPONSE']._serialized_start=140
  _globals['_HEALTHRESPONSE']._serialized_end=172
  _globals['_INFERENCESERVICE']._serialized_start=175
  _globals['_INFERENCESERVICE']._serialized_end=328
# @@protoc_insertion_point(module_scope)
